version: '3'

services:

  myapp-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vise
      - MYSQL_USER=root
      - MYSQL_PASSWORD=qwe123
    ports:
      - 3306:3306
    networks:
      - vise-mysql
      
  myapp-main:
    image: vise/viseproducts:latest
    networks:
      - vise-mysql
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_USER=root
      - DATABASE_PASSWORD=mysql
      - DATABASE_NAME=test
      - DATABASE_PORT=3306
   
networks:
  employee-mysql: 